"use client"

import { BookOpen, Clock, Target, Play, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Theme, ExamStats } from "@/lib/exam/types"
import { getThemeClasses } from "@/lib/exam/theme-classes"

interface StartScreenProps {
  darkMode: boolean
  currentTheme: Theme
  generationPrompt: string
  setGenerationPrompt: (value: string) => void
  questionCount: number
  setQuestionCount: (value: number) => void
  aiModel: string
  allowedModels: string[]
  remainingCredits: number | null
  remainingQuestionsForModel?: number
  setAiModel: (value: string) => void
  isModelConfigLoading: boolean
  difficulty: string
  setDifficulty: (value: string) => void
  examMode: "practice" | "timed" | "survival"
  setExamMode: (value: "practice" | "timed" | "survival") => void
  isGenerating: boolean
  generationError: string
  generationCooldownLeft: number
  stats: ExamStats
  onStart: () => void
}

const EXAM_MODES = [
  { value: "practice" as const, label: "Practice", desc: "Immediate feedback", icon: BookOpen },
  { value: "timed" as const, label: "Timed", desc: "Race against time", icon: Clock },
  { value: "survival" as const, label: "Survival", desc: "One mistake ends it", icon: Target },
]

export function StartScreen({
  darkMode,
  currentTheme,
  generationPrompt,
  setGenerationPrompt,
  questionCount,
  setQuestionCount,
  aiModel,
  allowedModels,
  remainingCredits,
  remainingQuestionsForModel,
  setAiModel,
  isModelConfigLoading,
  difficulty,
  setDifficulty,
  examMode,
  setExamMode,
  isGenerating,
  generationError,
  generationCooldownLeft,
  stats,
  onStart,
}: StartScreenProps) {
  const themeClasses = getThemeClasses(currentTheme)

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-2">
        <Card className={`${darkMode ? "bg-gray-800 border-gray-700" : ""}`}>
          <CardHeader>
            <CardTitle className={`text-3xl ${darkMode ? "text-white" : ""}`}>
              Generate Your Exam
            </CardTitle>
            <p className={`${darkMode ? "text-gray-300" : "text-gray-600"}`}>
              Questions are generated by OpenRouter and saved to Supabase.
            </p>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-2">
              <label className={`block text-sm font-medium ${darkMode ? "text-white" : ""}`}>
                Topic / Prompt
              </label>
              <Textarea
                value={generationPrompt}
                onChange={(e) => setGenerationPrompt(e.target.value)}
                placeholder="Example: JavaScript fundamentals for beginners"
                className="min-h-24"
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="space-y-2">
                <label className={`block text-sm font-medium ${darkMode ? "text-white" : ""}`}>
                  Question Count
                </label>
                <Input
                  type="number"
                  min={1}
                  max={50}
                  value={questionCount}
                  onChange={(e) => setQuestionCount(Math.min(50, Math.max(1, Number(e.target.value) || 1)))}
                />
              </div>

              <div className="space-y-2">
                <label className={`block text-sm font-medium ${darkMode ? "text-white" : ""}`}>
                  Difficulty
                </label>
                <Select value={difficulty} onValueChange={setDifficulty}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="mixed">Mixed</SelectItem>
                    <SelectItem value="easy">Easy</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="hard">Hard</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <label className={`block text-sm font-medium ${darkMode ? "text-white" : ""}`}>
                  AI Model
                </label>
                <Select value={aiModel} onValueChange={setAiModel} disabled={isModelConfigLoading}>
                  <SelectTrigger>
                    <SelectValue placeholder={isModelConfigLoading ? "Loading from backend..." : "Select model"} />
                  </SelectTrigger>
                  <SelectContent>
                    {allowedModels.map((model) => (
                      <SelectItem key={model} value={model}>
                        {model}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <p className={`text-xs ${darkMode ? "text-gray-300" : "text-gray-600"}`}>
                  {typeof remainingQuestionsForModel === "number"
                    ? `Estimated remaining: ${remainingQuestionsForModel} questions${typeof remainingCredits === "number" ? ` (${remainingCredits.toFixed(2)} credits left)` : ""}`
                    : "Usage estimate unavailable for this key/model."}
                </p>
              </div>
            </div>

            <div>
              <label className={`block text-sm font-medium mb-2 ${darkMode ? "text-white" : ""}`}>
                Exam Mode
              </label>
              <div className="grid grid-cols-3 gap-2">
                {EXAM_MODES.map((mode) => (
                  <button
                    key={mode.value}
                    type="button"
                    onClick={() => setExamMode(mode.value)}
                    className={`p-4 rounded-lg border-2 transition-all ${
                      examMode === mode.value
                        ? `${themeClasses.primary.border500} ${themeClasses.primary.bg50} ${darkMode ? "bg-opacity-20" : ""}`
                        : darkMode
                          ? "border-gray-600 bg-gray-700 hover:border-gray-500"
                          : "border-gray-200 bg-white hover:border-gray-300"
                    }`}
                  >
                    <mode.icon
                      className={`h-6 w-6 mx-auto mb-2 ${
                        examMode === mode.value ? themeClasses.primary.text500 : "text-gray-400"
                      }`}
                    />
                    <div className={`font-medium ${darkMode ? "text-white" : ""}`}>{mode.label}</div>
                    <div className={`text-xs ${darkMode ? "text-gray-300" : "text-gray-500"}`}>
                      {mode.desc}
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {generationError ? (
              <p className="text-sm text-red-500">{generationError}</p>
            ) : null}

            <Button
              onClick={onStart}
              size="lg"
              className="w-full"
              disabled={
                isGenerating ||
                isModelConfigLoading ||
                generationCooldownLeft > 0 ||
                !generationPrompt.trim() ||
                !aiModel.trim()
              }
            >
              {isGenerating ? <Loader2 className="h-5 w-5 mr-2 animate-spin" /> : <Play className="h-5 w-5 mr-2" />}
              {isGenerating
                ? "Generating Questions..."
                : generationCooldownLeft > 0
                  ? `Wait ${generationCooldownLeft}s`
                  : `Generate & Start (${questionCount} questions)`}
            </Button>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <Card className={`${darkMode ? "bg-gray-800 border-gray-700" : ""}`}>
          <CardHeader>
            <CardTitle className={`text-lg ${darkMode ? "text-white" : ""}`}>Quick Stats</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex justify-between">
              <span className={darkMode ? "text-gray-300" : "text-gray-600"}>Best Score</span>
              <span className={`font-bold ${themeClasses.primary.text500}`}>{stats.bestScore}%</span>
            </div>
            <div className="flex justify-between">
              <span className={darkMode ? "text-gray-300" : "text-gray-600"}>Average</span>
              <span className={darkMode ? "text-white" : ""}>{stats.averageScore}%</span>
            </div>
            <div className="flex justify-between">
              <span className={darkMode ? "text-gray-300" : "text-gray-600"}>Total Exams</span>
              <span className={darkMode ? "text-white" : ""}>{stats.totalExams}</span>
            </div>
            <div className="flex justify-between">
              <span className={darkMode ? "text-gray-300" : "text-gray-600"}>Best Streak</span>
              <span className={`font-bold ${themeClasses.accent.text500}`}>{stats.streak}</span>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
